# Generated by Django 5.1.5 on 2025-02-13 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_shop', models.CharField(default='', max_length=50)),
                ('descript_shop', models.TextField(null=True)),
                ('adresse_shop', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_categorie', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_mod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_role', models.CharField(default='', max_length=50)),
                ('descript_role', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(default='', max_length=50)),
                ('descript_type', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(default='', max_length=50)),
                ('email_client', models.EmailField(default=None, max_length=254, unique=True)),
                ('tel_client', models.CharField(max_length=20, unique=True)),
                ('adresse_client', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.boutique')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur_user', models.CharField(default='+225', max_length=5, null=True)),
                ('tel_user', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.role')),
            ],
        ),
        migrations.AddField(
            model_name='boutique',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.customuser'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_fact', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('num_fact', models.CharField(max_length=100, null=True)),
                ('prixHT_fact', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tva_fact', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('reduc_fact', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('statePaie_fact', models.CharField(max_length=20, null=True)),
                ('dateEch_fact', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.boutique')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(default='', max_length=100, unique=True)),
                ('contact_fournisseur', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresse_fournisseur', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_paie', models.CharField(max_length=50, unique=True)),
                ('date_paie', models.DateField(null=True)),
                ('montant_paie', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('refTrans_paie', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.facture')),
                ('mode_paie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.model')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('libelle_produit', models.CharField(max_length=100, unique=True)),
                ('descript_produit', models.TextField(blank=True, null=True)),
                ('marque_produit', models.CharField(max_length=30, null=True)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('stock_produit', models.IntegerField(default=0)),
                ('seuil_produit', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.boutique')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='FactureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_factI', models.SmallIntegerField(default=0)),
                ('prix_factI', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('facture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.facture')),
                ('produit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reap', models.CharField(max_length=50, unique=True)),
                ('date_reap', models.DateField(null=True)),
                ('quantite_reap', models.SmallIntegerField(default=0)),
                ('prix_reap', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.boutique')),
                ('fournisseur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reapI', models.SmallIntegerField(default=0)),
                ('prix_reapI', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('produit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.produit')),
                ('reappro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.reapprovisionnement')),
            ],
        ),
        migrations.AddField(
            model_name='boutique',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.type'),
        ),
    ]
