# Generated by Django 5.1.5 on 2025-02-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomShop', models.CharField(max_length=50)),
                ('descriptShop', models.TextField(null=True)),
                ('adresseShop', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_categorie', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFournisseur', models.CharField(max_length=100, unique=True)),
                ('contactFournisseur', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('emailFournisseur', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresseFournisseur', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleMod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleRole', models.CharField(max_length=50)),
                ('descriptRole', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleType', models.CharField(max_length=50)),
                ('descriptType', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=50)),
                ('emailClient', models.EmailField(max_length=254, unique=True)),
                ('telClient', models.CharField(max_length=20, unique=True)),
                ('adresseClient', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.boutique')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateurUser', models.CharField(default='+225', max_length=5, null=True)),
                ('telUser', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.role')),
            ],
        ),
        migrations.AddField(
            model_name='boutique',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.customuser'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFact', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('numFact', models.CharField(max_length=100, null=True)),
                ('prixHTFact', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tvaFact', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('reducFact', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('statePaieFact', models.CharField(max_length=20, null=True)),
                ('dateEchFact', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPaie', models.CharField(max_length=50)),
                ('datePaie', models.DateField(null=True)),
                ('montantPaie', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('refTransPaie', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.facture')),
                ('modePaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.model')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idProduit', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('libelleProduit', models.CharField(max_length=100, unique=True)),
                ('descriptProduit', models.TextField(blank=True, null=True)),
                ('marqueProduit', models.CharField(max_length=30, null=True)),
                ('prixProduit', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('stockProduit', models.IntegerField(default=0)),
                ('seuilProduit', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.boutique')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestcom_api.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='FactureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteFactI', models.SmallIntegerField()),
                ('prixFactI', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numReap', models.CharField(max_length=50)),
                ('dateReap', models.DateField(null=True)),
                ('quantiteReap', models.SmallIntegerField()),
                ('prixReap', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteReapI', models.SmallIntegerField()),
                ('prixReap', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.produit')),
                ('reappro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.reapprovisionnement')),
            ],
        ),
        migrations.AddField(
            model_name='boutique',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestcom_api.type'),
        ),
    ]
